import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import localFont from "next/font/local"
// import font from "../pu"

const outfit = localFont({
  src: [
    {
      path: "../public/fonts/Outfit-VariableFont_wght.ttf",

      style: "normal",
    },
  ],
  variable: "--font-outfit",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>{children}</body>
    </html>
  )
}
